
alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

server:
  ingress:
    enabled: true
    hosts:
     - prometheus.local
  extraFlags:
    - web.enable-lifecycle
    - web.enable-remote-write-receiver
  persistentVolume:
    enabled: true
    size: 1Gi

configmapReload:
  prometheus:
    enabled: false
