mode: deployment

config:
  exporters:
    logging:
      loglevel: info
    otlphttp:
      endpoint: http://tempo-distributed-distributor.tempo-distributed:4318
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
#    prometheus:
#      config:
#        scrape_configs:
#          - job_name: opentelemetry-collector
#            scrape_interval: 10s
#            static_configs:
#              - targets:
#                  - ${MY_POD_IP}:8888
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      traces:
        exporters:
          - logging
          - otlphttp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp

